"use client";
import RootProvider from "@/providers/provider";
import "@rainbow-me/rainbowkit/styles.css";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import useEscroguard from "@/hooks/escroguard";
import usePolybase from "@/hooks/polybase";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "100", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const polybase = usePolybase();
  useEscroguard(polybase);

  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
